// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract TestIconOmega {
    uint256 value; // [omega state]
    constructor() {
            value = 42;
        }
    function getValue() public view  returns (uint256) {
            return value;
        }
}
