use anchor_lang::prelude::*;

// Generated by OMEGA native codegen (alpha)
#[account]
pub struct State {
    // TODO: mappings omitted; implement account-backed map
}

#[program]
pub mod NamedOutputsExample {
    use super::*;
}

