// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract NestedArraysExample {
    function firstOrEmpty(string[][] memory items) public pure returns (string memory) {
            if (items.length > 0 && items[0].length > 0) {
                return items[0][0];
            }
            return "";
        }
    function pickBytes(bytes[][] memory arr) public pure returns (bytes memory) {
            if (arr.length > 0 && arr[0].length > 0) {
                return arr[0][0];
            }
    bytes memory empty = bytes("");
            return empty;
        }
}
