// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract StringLengthExample {
    function strLen(string memory s) returns (uint256) {
            return bytes(s).length;
        }
    function bytesLen(bytes memory b) returns (uint256) {
            return b.length;
        }
    function mixed(string[] memory ss) returns (uint256) {
            if (ss.length > 0) {
                return bytes(ss[0]).length;
            }
            return 0;
        }
}
