// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract TupleNestedExample {
    function retTupleDyn(string memory a, int32[] memory b) public returns (string memory, int32[] memory) {
            return (a, b);
        }
    function processNested(string[][] memory items) public returns (string memory) {
            // Return first item if exists, else empty
            if (items.length > 0 && items[0].length > 0) {
                return items[0][0];
            }
            return "";
        }
}
