// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract TupleMultipleDynamicExample {
    function retMulti(string memory a, bytes memory b, uint256[] memory c) public pure returns (string memory, bytes memory, uint256[] memory) {
            return (a, b, c);
        }
    function useLengths(uint256[] memory xs, string[] memory ss) public pure returns (uint256) {
    uint256 sum = 0;
            if (xs.length > 0) {
                // Just return first element for simplicity
                return xs[0];
            }
            if (ss.length > 0) {
                // Return the count of strings for coverage
                return ss.length;
            }
            return sum;
        }
}
