// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract TupleDeepDynamicExample {
    function retNested(string memory a, bytes memory b, uint256[] memory nums, string[][] memory labels) returns (string memory, bytes memory, uint256[] memory, string[][] memory) {
            return (a, b, nums, labels);
        }
    function lens(bytes memory bb, string[][] memory names) returns (uint256) {
            if (names.length > 0 && names[0].length > 0) {
                // first label length
                return bytes(names[0][0]).length;
            }
            return bb.length;
        }
}
