// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract RangeTransformExt {
    function main() pure  public {
    uint256 sum = 0;
            // Ascending step 2
    for (uint256 i = 0; i < 10; i += 2) {
                sum = sum + i;
            }
            // Ascending step 3
    for (uint256 p = 0; p < 9; p += 3) {
                sum = sum + p;
            }
            // Descending step -3 (signed loop)
    for (int256 j = 10; j > 0; j -= 3) {
                sum = sum + j;
            }
            // Variable-based bounds (unit step)
    uint256 a = 5;
    uint256 b = 5;
    for (uint256 k = a; k < b; k += 1) {
                sum = sum + k;
            }
            // Variable-defined step (ascending)
    uint256 step2 = 2;
    for (uint256 q = 0; q < 8; q += step2) {
                sum = sum + q;
            }
            // Zero-to-zero range (no iterations)
    for (uint256 m = 0; m < 0; m += 1) {
                sum = sum + m;
            }
            // Large step
    for (uint256 n = 0; n < 100; n += 20) {
                sum = sum + n;
            }
        }
}
