// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract main {
    function main() public  pure{
    int32 x = 10;
    int32 y = 20;
        
    int32 sum = add(x, y);
    int32 product = multiply(x, y);
        
        print("Sample OMEGA Project");
        print_int(sum);
        print_int(product);
    }
    function print_int(value: int32) public  pure{
        print(value);
    }
}
