// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract math {
    function add(a: int32, b: int32) public  pure-> int32 {
        return a + b;
    }
    function subtract(a: int32, b: int32) public  pure-> int32 {
        return a - b;
    }
    function multiply(a: int32, b: int32) public  pure-> int32 {
        return a * b;
    }
    function divide(a: int32, b: int32) public  pure-> int32 {
        if (b == 0) {
            return 0;
        }
        return a / b;
    }
    function power(base: int32, exponent: int32) public  pure-> int32 {
    int32 result = 1;
    int32 i = 0;
        
        while i < exponent {
            result = result * base;
            i = i + 1;
        }
        
        return result;
    }
}
