// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// Generated by OMEGA native codegen (alpha)
    // State & events translated from OMEGA
    // NOTE: Review and adjust for full correctness.

contract utils {
    function is_positive(value: int32) public  pure-> bool {
        return value > 0;
    }
    function is_negative(value: int32) public  pure-> bool {
        return value < 0;
    }
    function is_zero(value: int32) public  pure-> bool {
        return value == 0;
    }
    function abs(value: int32) public  pure-> int32 {
        if (value < 0) {
            return 0 - value;
        }
        return value;
    }
    function max(a: int32, b: int32) public  pure-> int32 {
        if (a > b) {
            return a;
        }
        return b;
    }
    function min(a: int32, b: int32) public  pure-> int32 {
        if (a < b) {
            return a;
        }
        return b;
    }
}
